on:
  push:
    branches:
      - "master"
  pull_request:

name: "Run tests"

jobs:
  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Setup stable toolchain"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true

      - name: "Run tests"
        run: |
          cargo test
